version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarpass
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonar
    networks:
      - sonarnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonarscanner:
    build:
      context: .
      dockerfile: Dockerfile  # Utilisation du Dockerfile mis à jour
    container_name: sonarscanner
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
    networks:
      - sonarnet
    command: >
      bash -c "cd /usr/src/app && composer install && ./vendor/bin/phpunit --coverage-clover coverage.xml && sonar-scanner"
    depends_on:
      - sonarqube
    volumes:
      - .:/usr/src/app  # Monte ton répertoire local avec le code source pour l'analyse

networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
