apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: app-container
          image: app-images:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "pedago01c.univ-avignon.fr"
            - name: DB_DATABASE
              value: "etd"
            - name: DB_USERNAME
              value: "uapv2200995"
            - name: DB_PASSWORD
              value: "xm4Quj"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
