name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout Code
      uses: actions/checkout@v3

    # Étape 2 : Configurer PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajusté pour correspondre à une version stable
        extensions: mbstring, intl, pdo, pgsql
        tools: composer

    # Étape 3 : Vérifier la version de PHP
    - name: Verify PHP Version
      run: php --version

    # Étape 4 : Diagnostiquer les fichiers du projet
    - name: List Files in src and tests
      run: |
        echo "Files in src:"
        ls -la src/
        echo "Files in tests:"
        ls -la tests/

    # Étape 5 : Nettoyer et réinstaller les dépendances
    - name: Remove Dependencies and Cache
      run: |
        rm -rf vendor composer.lock
        composer clear-cache
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist
    - name: Dump Autoload
      run: composer dump-autoload -o

    # Étape 6 : Vérifier la configuration PSR-4
    - name: Show PSR-4 Autoload Map
      run: cat vendor/composer/autoload_psr4.php

    # Étape 7 : Exécuter les tests PHPUnit
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    # Étape 8 : Installer et configurer Snyk
    - name: Install Snyk
      run: npm install -g snyk
    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    # Étape 9 : Lancer l'analyse des dépendances
    - name: Snyk Dependency Test
      run: snyk test --all-projects

    # Étape 10 : Surveiller les dépendances avec Snyk
    - name: Monitor Dependencies with Snyk
      run: snyk monitor
