name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout Code
      uses: actions/checkout@v3

    # Étape 2 : Configurer PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Version stable recommandée
        extensions: mbstring, intl, pdo, pgsql, xdebug
        tools: composer

    # Étape 3 : Vérifier la version de PHP
    - name: Verify PHP Version
      run: php --version

    # Étape 4 : Diagnostiquer les fichiers du projet
    - name: List Files in src and tests
      run: |
        echo "Files in src:"
        ls -la src/
        echo "Files in tests:"
        ls -la tests/

    # Étape 5 : Nettoyer et réinstaller les dépendances
    - name: Remove Dependencies and Cache
      run: |
        rm -rf vendor composer.lock
        composer clear-cache
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist
    - name: Dump Autoload
      run: composer dump-autoload -o

    # Étape 6 : Vérifier la configuration PSR-4
    - name: Show PSR-4 Autoload Map
      run: cat vendor/composer/autoload_psr4.php

    # Étape 7 : Configurer Xdebug pour la couverture
    - name: Configure Xdebug
      run: |
        mkdir -p /usr/local/etc/php/conf.d
        echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        echo "xdebug.start_with_request=no" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    # Étape 8 : Exécuter les tests PHPUnit avec couverture
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    # Étape 9 : Installer et configurer Snyk
    - name: Install Snyk
      run: npm install -g snyk
    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    # Étape 10 : Lancer l'analyse des dépendances avec Snyk
    - name: Snyk Dependency Test
      run: snyk test --all-projects

    # Étape 11 : Surveiller les dépendances avec Snyk
    - name: Monitor Dependencies with Snyk
      run: snyk monitor

    # Étape 12 : Analyser avec SonarQube
    - name: SonarQube Analysis
      env:
        SONAR_HOST_URL: http://<IP_SONARQUBE>:9000
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-php-project \
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.sources=src
