name: CI for PHP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer PHP et les dépendances
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Utilisez la version PHP que vous utilisez
          extensions: mbstring, xml, bcmath  # Ajoutez les extensions PHP nécessaires

      # Étape 3 : Installer les dépendances Composer
      - name: Install dependencies
        run: |
          composer install --no-interaction

      # Étape 4 : Exécuter PHPUnit avec génération du rapport de couverture
      - name: Run PHPUnit tests with coverage
        run: |
          vendor/bin/phpunit --coverage-xml=coverage-report.xml

      # Étape 5 : Télécharger le rapport de couverture sur Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Utilisez le secret CODECOV_TOKEN pour l'authentification
          file: coverage-report.xml  # Fichier de couverture généré
