name: CI for PHP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer PHP 8.2
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath  # Ajoutez les extensions nécessaires

      # Étape 3 : Installer les dépendances Composer
      - name: Install dependencies
        run: |
          composer install --no-interaction

      # Étape 4 : Ajouter les permissions d'exécution pour PHPUnit
      - name: Set executable permissions for PHPUnit
        run: chmod +x vendor/bin/phpunit

      # Étape 5 : Exécuter PHPUnit avec génération de couverture
      - name: Run PHPUnit tests with coverage
        run: |
          vendor/bin/phpunit --coverage-xml=coverage-report.xml

      # Étape 6 : Télécharger le rapport de couverture sur Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Utilisation du secret CODECOV_TOKEN
          file: coverage-report.xml  # Fichier de couverture généré par PHPUnit
