name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout Code
      uses: actions/checkout@v3

    # Étape 2 : Configurer PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo, pgsql, xdebug, dom, curl
        tools: composer

    # Étape 3 : Installer Xdebug (si nécessaire)
    - name: Configure Xdebug
      run: |
        mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
        echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        echo "xdebug.start_with_request=no" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

    # Étape 4 : Vérifier les fichiers du projet
    - name: List Files in src and tests
      run: |
        echo "Files in src:"
        ls -la src/
        echo "Files in tests:"
        ls -la tests/

    # Étape 5 : Nettoyer et réinstaller les dépendances
    - name: Remove Dependencies and Cache
      run: |
        rm -rf vendor composer.lock
        composer clear-cache
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    # Étape 6 : Exécuter les tests PHPUnit avec couverture
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    # Étape 7 : Analyser avec SonarQube
    - name: SonarQube Analysis
      env:
        SONAR_HOST_URL: http://<IP_SONARQUBE>:9000
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-php-project \
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.sources=src

    # Étape 8 : Installer et configurer Snyk
    - name: Install Snyk
      run: npm install -g snyk
    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    # Étape 9 : Lancer l'analyse des dépendances avec Snyk
    - name: Snyk Dependency Test
      run: snyk test --all-projects

    # Étape 10 : Surveiller les dépendances avec Snyk
    - name: Monitor Dependencies with Snyk
      run: snyk monitor
