jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify PHP Version
        run: php --version

      - name: List Files in src and tests
        run: |
          ls -la src/
          ls -la tests/

      - name: Dump Autoload
        run: composer dump-autoload -o

      - name: Show PSR-4 Autoload Map
        run: cat vendor/composer/autoload_psr4.php

      - name: Run Tests
        run: vendor/bin/phpunit --filter DatabaseConnectionTest
